# Generated by Django 3.0.5 on 2020-06-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi_app', '0006_auto_20200610_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment_areas',
            name='area_payment',
            field=models.CharField(default='Sin precio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_payment',
            field=models.CharField(default='Sin precio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_payment',
            field=models.CharField(default='Sin precio', max_length=500, null=True),
        ),
    ]
